name: Build Mumble for macOS (ARM)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build Mumble
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2

      - name: Install Nix with Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Run Nix Build
        run: |
          nix build .

      - name: Find, Verify, and Copy Mumble.app
        run: |
          RESULT_PATH=$(cd result && pwd -P)
          MUMBLE_APP_PATH="$RESULT_PATH/Mumble.app"

          if [ -d "$MUMBLE_APP_PATH" ]; then
            echo "Found Mumble.app at $MUMBLE_APP_PATH"
            cp -R "$MUMBLE_APP_PATH" Mumble.app
          else
            echo "Error: Unable to locate Mumble.app in $RESULT_PATH"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MumbleApp-${{ github.sha }}
          path: Mumble.app
